name = "it-feels-proxy"
main = "src/index.ts"
compatibility_date = "2024-03-01"

[vars]
ENVIRONMENT = "production"
DEFAULT_AUDIO_QUALITY = "320kbps"
API_SECRET = "development_secret_123"
YT_DLP_BASE_URL = "https://it-feels-android.onrender.com"
TELEGRAM_BOT_TOKEN = "8876729145:AAEr_vV4ZQYPKBBdLYWw2dqnSjrDGHwdU9w"

[[kv_namespaces]]
binding = "SEARCH_CACHE"
id = "3cc3e8229403480a8aba34a1f1750550"
