// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuzNmgNgtMgE7SGZn86jjpTx8ja0Y5la0',
    appId: '1:871513419979:web:537df62b89b620e3dcab4e',
    messagingSenderId: '871513419979',
    projectId: 'it-feels',
    authDomain: 'it-feels.firebaseapp.com',
    databaseURL: 'https://it-feels-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'it-feels.firebasestorage.app',
    measurementId: 'G-3V8VKQK10M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs3YpqQXYA4xUHYeV9ZzrkvypVr2alXn0',
    appId: '1:871513419979:android:09cf99d8f828f51edcab4e',
    messagingSenderId: '871513419979',
    projectId: 'it-feels',
    databaseURL: 'https://it-feels-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'it-feels.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrX6fCTOLqKkx4aeXhXqqfHOuJOP8N4vQ',
    appId: '1:871513419979:ios:4e2edbe14ef3f5cbdcab4e',
    messagingSenderId: '871513419979',
    projectId: 'it-feels',
    databaseURL: 'https://it-feels-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'it-feels.firebasestorage.app',
    iosClientId: '871513419979-0116coptppjehfnkjeogq5s4bmdv7184.apps.googleusercontent.com',
    iosBundleId: 'com.itfeels.music',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrX6fCTOLqKkx4aeXhXqqfHOuJOP8N4vQ',
    appId: '1:871513419979:ios:2c1d2929c216f080dcab4e',
    messagingSenderId: '871513419979',
    projectId: 'it-feels',
    databaseURL: 'https://it-feels-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'it-feels.firebasestorage.app',
    iosClientId: '871513419979-iue97ao88vmd7eqbjmvb8sc585ollhqj.apps.googleusercontent.com',
    iosBundleId: 'com.pixelplayer.saavn.pixelPlayerSaavn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuzNmgNgtMgE7SGZn86jjpTx8ja0Y5la0',
    appId: '1:871513419979:web:537df62b89b620e3dcab4e', // Synced with Web App ID
    messagingSenderId: '871513419979',
    projectId: 'it-feels',
    authDomain: 'it-feels.firebaseapp.com',
    databaseURL: 'https://it-feels-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'it-feels.firebasestorage.app',
    measurementId: 'G-FWN1NHL61X',
  );
}
